#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np
import matplotlib.pyplot as plt


# In[2]:


#import data generated by fig3_tcTheory.ipynb and fig3_order_parameter.ipynb

path='summaryTc/'

chiPairs_domain=np.load(path+'tc_chi_domains.npy')
chiPairs_rand=np.load(path+'tc_chi_rand.npy')
chiPairs_stoich=np.load(path+'tc_chi_stoich.npy')

theoryPairs_domain=np.load(path+'tc_theory_domains.npy')
theoryPairs_rand=np.load(path+'tc_theory_rand.npy')
theoryPairs_stoich=np.load(path+'tc_theory_stoich.npy')


# In[3]:


#get color data
prop_cycle = plt.rcParams['axes.prop_cycle']
colors = prop_cycle.by_key()['color']


# In[4]:


#summary
plt.figure(figsize=(8,6))
ax1=plt.gca()

#tc theory values
plt.errorbar(theoryPairs_domain[:,1],theoryPairs_domain[:,0],xerr=theoryPairs_domain[:,2],fmt='.',color=colors[1],markersize=10,label='Domains')
plt.errorbar(theoryPairs_rand[:,1],theoryPairs_rand[:,0],xerr=theoryPairs_rand[:,2],fmt='.',color=colors[0],markersize=10,label='Scrambled')
plt.errorbar(theoryPairs_stoich[:,1],theoryPairs_stoich[:,0],xerr=theoryPairs_stoich[:,2],fmt='.',color='k',markersize=10,label='$a \\neq b$')
plt.legend(title='Sequence type',title_fontsize=22,fontsize=22)
plt.tick_params(axis='both',labelsize=18)
plt.ylabel('Theory $T_\mathrm{c}$',fontsize=22)


ax2=ax1.twinx()
#chi values
chiMarker='*'
chiMarkerSize=8
ax2.errorbar(chiPairs_domain[:,1],chiPairs_domain[:,0],xerr=chiPairs_domain[:,2],fmt=chiMarker,color=colors[1],markersize=chiMarkerSize,label='Domains')
ax2.errorbar(chiPairs_rand[:,1],chiPairs_rand[:,0],xerr=chiPairs_rand[:,2],fmt=chiMarker,color=colors[0],markersize=chiMarkerSize,label='Scrambled')
ax2.errorbar(chiPairs_stoich[:,1],chiPairs_stoich[:,0],xerr=chiPairs_stoich[:,2],fmt=chiMarker,color='k',markersize=chiMarkerSize,label='$a \\neq b$')
plt.ylabel('Condensation parameter $X$',fontsize=22)
plt.tick_params(axis='both',labelsize=18)
ax2.set_ylim(ymax=-10)

ax1.set_xlabel('Simulation $T_\mathrm{c}$',fontsize=22)
plt.tight_layout()

# plt.savefig('fig3_tC_trends_option2.svg')
# plt.savefig('fig3_tC_trends_option2.png')




#summary, match axes
plt.figure(figsize=(8,6))
ax1=plt.gca()

labelSize=24

#tc theory values
plt.errorbar(theoryPairs_domain[:,1],theoryPairs_domain[:,0],xerr=theoryPairs_domain[:,2],fmt='.',color=colors[0],markersize=12,label='Domains')
plt.errorbar(theoryPairs_rand[:,1],theoryPairs_rand[:,0],xerr=theoryPairs_rand[:,2],fmt='*',color=colors[0],markersize=11,label='Scrambled')
plt.errorbar(theoryPairs_stoich[:,1],theoryPairs_stoich[:,0],xerr=theoryPairs_stoich[:,2],fmt='s',markerfacecolor='none',color=colors[0],markersize=8,label='$a \\neq b$')
# plt.legend(title='Sequence type',title_fontsize=22,fontsize=22)
plt.tick_params(axis='both',labelsize=18)
plt.tick_params(axis='y',labelcolor=colors[0])
plt.ylabel('Theory $T_\mathrm{c}$',fontsize=labelSize,color=colors[0])


ax2=ax1.twinx()
#chi values

ax2.errorbar(chiPairs_domain[:,1],chiPairs_domain[:,0],xerr=chiPairs_domain[:,2],fmt='.',color=colors[1],markersize=12,label='Domains')
ax2.errorbar(chiPairs_rand[:,1],chiPairs_rand[:,0],xerr=chiPairs_rand[:,2],fmt='*',color=colors[1],markersize=11,label='Scrambled')
ax2.errorbar(chiPairs_stoich[:,1],chiPairs_stoich[:,0],xerr=chiPairs_stoich[:,2],fmt='s',markerfacecolor='none',color=colors[1],markersize=8,label='$a \\neq b$')
plt.ylabel('Condensation parameter $\Psi$',fontsize=labelSize,color=colors[1])
plt.tick_params(axis='both',labelsize=18)
plt.tick_params(axis='y',labelcolor=colors[1])
ax2.set_ylim(ymax=-15.8)

ax1.set_xlabel('Simulation $T_\mathrm{c}$',fontsize=labelSize)

plt.tight_layout()


# plt.savefig('fig3_tC_trends_curveCollapse.svg')


# In[8]:




